Update the version of final_project to 2022
gdut-dynamic-x/missing-semester pull request #57
Opened 2022-11-01 15:29 UTC by irvingskr

- Change all the `2021` to `2022` in README.md.
- Delete the request of create a label.
- Delete the folder of _2021-finalproject to prevent plagiarism.

2022-11-01 15:47 UTC, LHTcode commented
不要直接把2021的作业都删了吧，我新建一个homework仓库，你把这些作业移到那里面去吧

2022-11-01 16:07 UTC, LHTcode requested changes

2022-11-01 16:07 UTC, LHTcode commented on 2022-finalproject/README.md
>  你可以在 MarkDown 文档中使用中文，但不要在 PR 的标题、描述及评论中使用中文
**评论和描述**中可以使用中文，只有标题和 commit 的内容不能使用中文，强调一下标题必须**非常简要地**概括你 pr 的内容，并且标题**不能写句号**，因为它不是一个句子，然后描述里面要较为详细地讲述你实际修改或实现的功能
就拿你这个标题来说，就应该改成类似 'Update 2022 filnal homework' 这样。

2022-11-01 16:12 UTC, irvingskr commented on 2022-finalproject/README.md
> -   - 被修改的检查项目为：作业提交文件夹变更为 `_2021-finalproject`
> 怎么把这个任务删了，这个任务才是第二阶段的关键点阿，你主仓库不修改文件夹名字，他们的merge就不会出现冲突的问题

这不是要等第二阶段的时候才放出来吗？

2022-11-01 16:21 UTC, LHTcode commented on 2022-finalproject/README.md
> -   - 被修改的检查项目为：作业提交文件夹变更为 `_2021-finalproject`
> > 怎么把这个任务删了，这个任务才是第二阶段的关键点阿，你主仓库不修改文件夹名字，他们的merge就不会出现冲突的问题
> 
> 这不是要等第二阶段的时候才放出来吗？

这个现在告诉他们也没关系的吧，到时候始终是要处理 merge 冲突的，考察的重点就是会不会处理 merge 冲突

2022-11-01 16:43 UTC, irvingskr commented on 2022-finalproject/README.md
> -   - 被修改的检查项目为：作业提交文件夹变更为 `_2021-finalproject`
> 

        怎么把这个任务删了，这个任务才是第二阶段的关键点阿，你主仓库不修改文件夹名字，他们的merge就不会出现冲突的问题

    这不是要等第二阶段的时候才放出来吗？

这个现在告诉他们也没关系的吧，到时候始终是要处理 merge 冲突的，考察的重点就是会不会处理 merge 冲突

ok

2022-11-01 16:43 UTC, irvingskr commented on 2022-finalproject/README.md
> -   - 被修改的检查项目为：作业提交文件夹变更为 `_2021-finalproject`
> 这个现在告诉他们也没关系的吧，到时候始终是要处理 merge 冲突的，考察的重点就是会不会处理 merge 冲突

ok

2022-11-01 16:52 UTC, irvingskr commented
@LHTcode all done.

2022-11-02 05:36 UTC, LHTcode approved these changes

2022-11-02 05:37 UTC, merged