Create LGX's PR
gdut-dynamic-x/missing-semester pull request #69
Opened 2022-11-03 09:22 UTC by emmm27427

2022-11-05 06:44 UTC, emmm27427 commented
I need review@reviewer

2022-11-06 09:07 UTC, emmm27427 reviewed
[README.md](https://github.com/gdut-dynamic-x/missing-semester/files/9945437/README.md)

2022-11-06 09:08 UTC, emmm27427 reviewed
[Git应用.md](https://github.com/gdut-dynamic-x/missing-semester/files/9945441/Git.md)

2022-11-07 12:01 UTC, irvingskr requested changes
Please show your work by committing your file in your repository.

2022-11-08 05:06 UTC, emmm27427 commented on LGX's PR
> +
[README.md](https://github.com/gdut-dynamic-x/missing-semester/files/9957777/README.md)

2022-11-08 05:12 UTC, emmm27427 reviewed
[README.md](https://github.com/gdut-dynamic-x/missing-semester/files/9957804/README.md)

2022-11-08 05:17 UTC, emmm27427 reviewed
[README.md](https://github.com/gdut-dynamic-x/missing-semester/files/9957827/README.md)

2022-11-08 05:17 UTC, emmm27427 commented on LGX's PR
> +
[README.md](https://github.com/gdut-dynamic-x/missing-semester/files/9957848/README.md)

2022-11-08 05:17 UTC, emmm27427 commented on LGX's PR
> +
#1.搜索引擎和论坛真得好重要，完全泡在CSDN里了。

#2.英语还需要提高啊（呜呜呜），一些纯英文档离开翻译插件根本读不了。

#3.感觉还有好多好多要学的，仍需努力。

2022-11-08 05:18 UTC, emmm27427 commented on LGX's PR
> +
[Git应用.md](https://github.com/gdut-dynamic-x/missing-semester/files/9957851/Git.md)

2022-11-08 05:18 UTC, emmm27427 commented on LGX's PR
> +
### <font size=8> **#1** </font>

##1准备工作

![](/home/emmm/图片/2022-11-06 15-17-02 的屏幕截图.png)

##2方式一（拉取最近一次提交到暂存区）![2022-11-06 15-30-21 的屏幕截图](/home/emmm/图片/2022-11-06 15-30-21 的屏幕截图.png)

##3方式二（回到修改前的状态，再添加到暂存区）![2022-11-06 15-41-23 的屏幕截图](/home/emmm/图片/2022-11-06 15-41-23 的屏幕截图.png)

###方式二好像错了，有一部分修改已经加入了暂存区

改为下图方式![2022-11-06 15-46-19 的屏幕截图](/home/emmm/图片/2022-11-06 15-46-19 的屏幕截图.png)

<font size=8> **#2** </font>

##1![2022-11-06 16-08-19 的屏幕截图](/home/emmm/图片/2022-11-06 16-08-19 的屏幕截图.png)

##2![2022-11-06 16-08-45 的屏幕截图](/home/emmm/图片/2022-11-06 16-08-45 的屏幕截图.png)

<font size=8> **#3** </font>

##1准备工作忘记截图了，这两个分支应该合并成功了吧？

![2022-11-06 16-53-22 的屏幕截图](/home/emmm/图片/2022-11-06 16-53-22 的屏幕截图.png)

##2![2022-11-06 16-57-25 的屏幕截图](/home/emmm/图片/2022-11-06 16-57-25 的屏幕截图.png)

2022-11-10 07:36 UTC, closed without merging