Test
gdut-dynamic-x/missing-semester pull request #75
Opened 2022-11-04 15:53 UTC by ZH970

Need to review.@reviewer

2022-11-09 07:59 UTC, irvingskr requested changes

2022-11-09 07:59 UTC, irvingskr commented on .github/ISSUE_TEMPLATE/translation.md
> ----
Why do you delete this filed?

2022-11-09 11:52 UTC, ZH970 commented on .github/ISSUE_TEMPLATE/translation.md
> ----
我当时以为那个是我自己不小心生成的。。（然后删掉了）我现在去源代码下载补回来

2022-11-09 12:09 UTC, ZH970 commented on .github/ISSUE_TEMPLATE/translation.md
> ----
Now is it OK? @irvingskr

2022-11-10 12:52 UTC, irvingskr approved these changes

2022-11-10 12:52 UTC, merged