Cc0h
gdut-dynamic-x/missing-semester pull request #81
Opened 2022-11-05 07:41 UTC by cc0h

preview my PR plz！

2022-11-05 07:52 UTC, irvingskr requested changes
Update your repository.

2022-11-05 08:01 UTC, cc0h commented
I have fixed some silly mistakes,review it again plz.

2022-11-05 08:34 UTC, irvingskr requested changes

2022-11-05 08:34 UTC, irvingskr commented on 2022-finalproject/README.md
> +2. 在IDEA中合并
Have you read the task seriously, you should new a directory named by your github id and put all your task file into it.

2022-11-05 09:06 UTC, cc0h commented on 2022-finalproject/README.md
> +2. 在IDEA中合并
忘记这点了，抱歉（）

2022-11-06 07:51 UTC, cc0h commented
已经把文件都放到文件夹里了

2022-11-06 09:45 UTC, irvingskr requested changes

2022-11-06 09:45 UTC, irvingskr commented on 2022-finalproject/cc0h/README.md
> +1. reset撤回修改后重新提交
Just reset?

2022-11-06 09:45 UTC, irvingskr commented on 2022-finalproject/cc0h/README.md
> +2. 在IDEA中合并
> **要求：** 编写一个文档，回答下列问题，这些问题的答案都应当使用 git 命令实现  
Please read the task carefully.

2022-11-06 13:31 UTC, cc0h commented on 2022-finalproject/cc0h/README.md
> +2. 在IDEA中合并
已解决

2022-11-07 12:41 UTC, irvingskr approved these changes

2022-11-09 07:54 UTC, irvingskr approved these changes

2022-11-09 07:55 UTC, merged