cappp666's PR
gdut-dynamic-x/missing-semester pull request #87
Opened 2022-11-05 17:25 UTC by cappp666

final-project

2022-11-06 09:07 UTC, cappp666 commented
@irvingskr I need review

2022-11-06 10:41 UTC, cappp666 commented on 2022-finalproject/README.md
> -1. 我们已经知道了合并分支可以使用 merge，但这不是唯一的方法，给出至少两种不同的合并分支的方式
Now is right,please review again

2022-11-07 12:50 UTC, irvingskr requested changes

2022-11-07 12:50 UTC, irvingskr commented on 2022-finalproject/cappp666/git.md
> +>>>>>>> e672afe461a24ac5bb9b128aed30826802039f49
You can have a look to the display effect of your md file.

2022-11-10 17:42 UTC, merged